### ISSUE TITLE
can you send FontUtils please?

### ISSUE THREAD

**Issue by Godwhitelight** [perzeroo/Astolfo-Like-Clickgui#1]
ty

**Comment by Godwhitelight** [comment]
and drawBorder.
and executorService.
and RenderUtils

**Comment by perzeroo** [comment]
You don't need executor service, fontutils are from herocode, renderutils are from liquidbounce

public static void drawBorder(float x, float y, float x2, float y2, float width, int color1) {
        glEnable(GL_BLEND);
        glDisable(GL_TEXTURE_2D);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        glEnable(GL_LINE_SMOOTH);

        glColor(color1);
        glLineWidth(width);

        glBegin(GL_LINE_LOOP);

        glVertex2d(x2, y);
        glVertex2d(x, y);
        glVertex2d(x, y2);
        glVertex2d(x2, y2);

        glEnd();

        glEnable(GL_TEXTURE_2D);
        glDisable(GL_BLEND);
        glDisable(GL_LINE_SMOOTH);
    }
